package com.example.sloppyseconds;

import androidx.appcompat.app.AppCompatActivity;

import android.os.AsyncTask;
import android.os.Bundle;
import android.widget.ProgressBar;

import org.json.JSONObject;
import org.jsoup.Jsoup;
import org.jsoup.select.Elements;
import org.jsoup.nodes.*;

import java.io.IOException;
import java.util.ArrayList;
import com.android.volley.*;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;

public class WebScraper extends AppCompatActivity {
    private String URL = "https://www.google.com/search";
    protected String barcode;
    public static ArrayList<String> stuff;

    public WebScraper(String barcode){
        this.barcode = barcode;

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_web_scraper);
    }


    private class Scrape extends AsyncTask<Void, Void, Void>{
        ProgressBar progressBar;

        @Override
        protected void onPreExecute(){
            super.onPreExecute();
            progressBar = new ProgressBar(WebScraper.this);
            progressBar.isIndeterminate();
        }

        @Override
        protected Void doInBackground(Void... voids){
            try{
                String searchURL = URL + "?q=" + barcode + "&num=5";
                //Connect to Google Search Engine
                Document document = Jsoup.connect(searchURL)
                        .userAgent("Mozilla/5.0 Chrome/W.X.Y.Z (compatible; Googlebot/2.1; " +
                                "+http://www.google.com/bot.html)").timeout(5000).get();

                //Find barcode on Google and scrapes first five links
                Elements str = document.select("a[href]");

                /* Cycles through Elements collection generated by first scrape and gets
                   link of first search result, then immediately breaks.
                 */
                String siteLink = null;
                for(Element link: str){
                    siteLink = link.attr("href");
                    break;
                }

                /*Connects to the first search result and gets product name from title of the
                  first website
                 */
                Document document1 = Jsoup.connect(siteLink).get();
                String productName = document1.title();
                stuff.add(productName);

            } catch(IOException e){
                e.printStackTrace();
            }
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid){
            super.onPostExecute(aVoid);

        }

    }
}

//STUFF arraylist should go in main method, not in an object

class EdamamScraper extends AppCompatActivity {

    //private String apID = "21924bbe";
    private String apiKey = "29ec211a5fdc4a2189244c2eb5776625";
    RequestQueue QUEUE;
    String URLHTTP = "https://api.spoonacular.com/recipes/findByIngredients?ingredients=";





}